config/routes.rb
Rails.application.routes.draw do
  root "missions#index"
  resources :planets
  resources :missions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mission.rb
class Mission < ApplicationRecord
  has_one :planet, dependent: :destroy

  def self.create_mission
    mission = Mission.new
    mission.name = [ "Apollo", "Artemis", "Ares", "Hermes", "Zeus", "Hera", "Athena", "Poseidon", "Hades", "Demeter" ].sample
    mission.name += " " + rand(1..99).to_s
    mission.status = "pending"
    mission.log = "Mission " + mission.name + " is pending."
    mission.level_oxygen = 100
    mission.level_food = 100
    mission.level_energy = 100
    mission
  end

  def is_alive?
    level_oxygen > 0 || level_food > 0
  end

  def offline?
    level_energy <= 0
  end

  def self.in_progress
    where(status: "pending")
  end
end

app/models/planet.rb
class Planet < ApplicationRecord
  belongs_to :mission
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: %i[ show edit update destroy ]

  # GET /missions or /missions.json
  def index
    @missions = Mission.all
  end

  # GET /missions/1 or /missions/1.json
  def show
  end

  # GET /missions/new
  def new
    @mission = Mission.create_mission
  end

  # GET /missions/1/edit
  def edit
  end

  # POST /missions or /missions.json
  def create
    @mission = Mission.new(mission_params)

    respond_to do |format|
      if @mission.save
        new_planet_discovered = create_planet(@mission)
        if new_planet_discovered
          format.html { redirect_to @mission, notice: "Mission was successfully created." }
          format.json { render :show, status: :created, location: @mission }
        else
          format.html { redirect_to @mission, notice: "Mission does not found planet" }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /missions/1 or /missions/1.json
  def update
    respond_to do |format|
      if @mission.update(mission_params)
        format.html { redirect_to @mission, notice: "Mission was successfully updated." }
        format.json { render :show, status: :ok, location: @mission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missions/1 or /missions/1.json
  def destroy
    @mission.destroy!

    respond_to do |format|
      format.html { redirect_to missions_path, status: :see_other, notice: "Mission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      @mission = Mission.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def mission_params
      params.expect(mission: [ :name, :status, :log, :level_oxygen, :level_food, :level_energy ])
    end

    def create_planet(mission)
      planet = Planet.new
      planet.name = "Q" + rand(1..9999).to_s + " # " + [ "N", "S", "W", "E" ].sample + "-"+rand(1..999).to_s + "°"
      planet.mission_id = mission.id
      planet.supply_oxygen = rand(-10..1)
      planet.supply_food = rand(-3..2)
      planet.supply_energy = rand(-10..10)
      planet.radiation = rand(0..10)
      planet.temperature = rand(-100..100)
      planet.save
    end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: %i[ show edit update destroy ]

  # GET /planets or /planets.json
  def index
    @planets = Planet.all
  end

  # GET /planets/1 or /planets/1.json
  def show
  end

  # GET /planets/new
  def new
    @planet = Planet.new
  end

  # GET /planets/1/edit
  def edit
  end

  # POST /planets or /planets.json
  def create
    @planet = Planet.new(planet_params)

    respond_to do |format|
      if @planet.save
        format.html { redirect_to @planet, notice: "Planet was successfully created." }
        format.json { render :show, status: :created, location: @planet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planets/1 or /planets/1.json
  def update
    respond_to do |format|
      if @planet.update(planet_params)
        format.html { redirect_to @planet, notice: "Planet was successfully updated." }
        format.json { render :show, status: :ok, location: @planet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planets/1 or /planets/1.json
  def destroy
    @planet.destroy!

    respond_to do |format|
      format.html { redirect_to planets_path, status: :see_other, notice: "Planet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planet
      @planet = Planet.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def planet_params
      params.expect(planet: [ :name, :mission_id, :supply_oxygen, :supply_food, :supply_energy, :radiation, :temperature ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Wilds Adventures" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/missions/_form.html.erb
<%= form_with(model: mission) do |form| %>
  <% if mission.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mission.errors.count, "error") %> prohibited this mission from being saved:</h2>

      <ul>
        <% mission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, disabled: true %>
    <%= form.hidden_field :name %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status, disabled: true %>
    <%= form.hidden_field :status %>
  </div>

  <div>
    <%= form.label :log, style: "display: block" %>
    <%= form.textarea :log %>
    <%= "add some log"%>
  </div>

  <div>
    <%= form.label :level_oxygen, style: "display: block" %>
    <%= form.number_field :level_oxygen %>
  </div>

  <div>
    <%= form.label :level_food, style: "display: block" %>
    <%= form.number_field :level_food %>
  </div>

  <div>
    <%= form.label :level_energy, style: "display: block" %>
    <%= form.number_field :level_energy %>
  </div>
  <br>
  <div>
    <%= form.submit "VIA!"%>
  </div>
<% end %>

app/views/missions/_mission.html.erb
<div id="<%= dom_id mission %>">
  <p>
    <strong>Name:</strong>
    <%= mission.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= mission.status %>
  </p>

  <p>
    <strong>Log:</strong>
    <%= mission.log %>
  </p>

  <p>
    <strong>Level oxygen:</strong>
    <%= mission.level_oxygen %>
  </p>

  <p>
    <strong>Level food:</strong>
    <%= mission.level_food %>
  </p>

  <p>
    <strong>Level energy:</strong>
    <%= mission.level_energy %>
  </p>

</div>

app/views/missions/edit.html.erb
<% content_for :title, "Editing mission" %>

<h1>Editing mission</h1>

<%= render "form", mission: @mission %>

<br>

<div>
  <%= link_to "Show this mission", @mission %> |
  <%= link_to "Back to missions", missions_path %>
</div>

app/views/missions/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Missions" %>

<%= link_to "New mission", new_mission_path %>

<h1>Missions</h1>

<div id="missions">
  <% @missions.each do |mission| %>
    <%= render mission %>
    <p>
      <%= link_to "Show this mission", mission %>
    </p>
  <% end %>
</div>

app/views/missions/new.html.erb
<% content_for :title, "New mission" %>

<h1>New mission</h1>

<%= render "form", mission: @mission %>

<br>

<div>
  <%= link_to "Back to missions", missions_path %>
</div>

app/views/missions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mission %>
  <br>
<p>Planet info</p>
  <%= "name: #{@mission.planet.name}" %>
  <br>
  <%= "supply_oxygen: #{@mission.planet.supply_oxygen}" %>
  <br>
  <%= "supply_food: #{@mission.planet.supply_food}" %>
  <br>
  <%= "supply_energy: #{@mission.planet.supply_energy}" %>
  <br>
  <%= "radiation: #{@mission.planet.radiation}" %>
  <br>
  <%= "temperature: #{@mission.planet.temperature}" %>
  <br>
  <br>
  <br>

<div>
  <%= link_to "Back to missions", missions_path %>

  <%= button_to "Destroy this mission", @mission, method: :delete %>
</div>

app/views/planets/_form.html.erb
<%= form_with(model: planet) do |form| %>
  <% if planet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(planet.errors.count, "error") %> prohibited this planet from being saved:</h2>

      <ul>
        <% planet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :mission_id, style: "display: block" %>
    <%= form.text_field :mission_id %>
  </div>

  <div>
    <%= form.label :supply_oxygen, style: "display: block" %>
    <%= form.number_field :supply_oxygen %>
  </div>

  <div>
    <%= form.label :supply_food, style: "display: block" %>
    <%= form.number_field :supply_food %>
  </div>

  <div>
    <%= form.label :supply_energy, style: "display: block" %>
    <%= form.number_field :supply_energy %>
  </div>

  <div>
    <%= form.label :radiation, style: "display: block" %>
    <%= form.number_field :radiation %>
  </div>

  <div>
    <%= form.label :temperature, style: "display: block" %>
    <%= form.number_field :temperature %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/planets/_planet.html.erb
<div id="<%= dom_id planet %>">
  <p>
    <strong>Name:</strong>
    <%= planet.name %>
  </p>

  <p>
    <strong>Mission:</strong>
    <%= planet.mission_id %>
  </p>

  <p>
    <strong>Supply oxygen:</strong>
    <%= planet.supply_oxygen %>
  </p>

  <p>
    <strong>Supply food:</strong>
    <%= planet.supply_food %>
  </p>

  <p>
    <strong>Supply energy:</strong>
    <%= planet.supply_energy %>
  </p>

  <p>
    <strong>Radiation:</strong>
    <%= planet.radiation %>
  </p>

  <p>
    <strong>Temperature:</strong>
    <%= planet.temperature %>
  </p>

</div>

app/views/planets/edit.html.erb
<% content_for :title, "Editing planet" %>

<h1>Editing planet</h1>

<%= render "form", planet: @planet %>

<br>

<div>
  <%= link_to "Show this planet", @planet %> |
  <%= link_to "Back to planets", planets_path %>
</div>

app/views/planets/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Planets" %>

<h1>Planets</h1>

<div id="planets">
  <% @planets.each do |planet| %>
    <%= render planet %>
    <p>
      <%= link_to "Show this planet", planet %>
    </p>
  <% end %>
</div>

<%= link_to "New planet", new_planet_path %>

app/views/planets/new.html.erb
<% content_for :title, "New planet" %>

<h1>New planet</h1>

<%= render "form", planet: @planet %>

<br>

<div>
  <%= link_to "Back to planets", planets_path %>
</div>

app/views/planets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @planet %>

<div>
  <%= link_to "Edit this planet", edit_planet_path(@planet) %> |
  <%= link_to "Back to planets", planets_path %>

  <%= button_to "Destroy this planet", @planet, method: :delete %>
</div>